### ISSUE TITLE
Meal Overview | Fix ingredients list

### ISSUE THREAD

**Issue by AninOnin** [cookomatic/cookomatic-app#45]
We need to update the ingredients loop (?) to only add the ingredients from the selected dishes. Right now it just puts all of them on the meal overview page.

(Also make sure that when a dish is removed, the ingredients associated with it are also removed.)

**Comment by rhefner1** [comment]
@AninOnin Good point. Right now, the ingredients list is being pulled from the mock schedule since we haven't merged the scheduler we were working on today. Since that's static API output, the ingredients list is static too.

I forgot about this, so thanks for bringing it to attention. I added a new comment on the scheduler: https://github.com/cookomatic/cookomatic-api/pull/40#issuecomment-292359103
